source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

def smart_home_pods
    pod 'YapDatabase', '~> 2.9'
end

target 'SmartHome' do
    smart_home_pods
end

target 'SmartHomeTests' do
    smart_home_pods
end
